# Generated by Django 2.1.5 on 2019-02-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('leader', models.CharField(max_length=160)),
                ('leader_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('assignee', models.CharField(max_length=160)),
                ('assignee_email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('notes', models.TextField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
