# Generated by Django 2.1.5 on 2019-03-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190304_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('OGN', 'On Going'), ('DED', 'Dead'), ('OHD', 'On hold'), ('PLA', 'Planning'), ('CPT', 'Complete'), ('RQD', 'Requested'), ('APD', 'Approved'), ('RJD', 'Rejected'), ('IDA', 'Idea')], default='IDA', max_length=3),
        ),
    ]
