# Generated by Django 2.1.5 on 2019-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('IDA', 'Idea'), ('RQD', 'Requested'), ('APD', 'Approved'), ('RJD', 'Rejected'), ('PLA', 'Planning'), ('OGN', 'Ongoing'), ('DED', 'Dead'), ('OHD', 'On hold'), ('CPT', 'Complete'), ('OVD', 'Overdue')], default='IDA', max_length=3),
        ),
    ]
