# Generated by Django 2.1.5 on 2019-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
