# Generated by Django 2.1.5 on 2019-03-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20190304_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risktype_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risks.RiskType'),
        ),
    ]
