# Generated by Django 2.1.5 on 2019-03-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('objective', models.TextField()),
                ('reach', models.TextField()),
                ('applies_to', models.TextField()),
                ('localization', models.TextField()),
                ('leader', models.CharField(max_length=160)),
                ('macroprocess_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.MacroProcess')),
            ],
        ),
    ]
